### ISSUE TITLE
1-2. 기능 분석 및 문서화(한글)

### ISSUE THREAD

**Issue by bootkorea** [alps-jbnu/JBNU-Litmus#8]
분석 및 문서화 대상
- 공식 Docs(https://docs.dmoj.ca/#/) 내 기재된 기능 전체

**Comment by dameun2224** [comment]
[DMOJ 관리자 기능  - 복사본.pdf](https://github.com/alps-jbnu/JBNU-Litmus/files/15294525/DMOJ.-.pdf)
